### ISSUE TITLE
Tag some issues as `good first issue`

### ISSUE THREAD

**Issue by Luro02** [bytecodealliance/cranelift#1228]
It would make it easier for new contributors, like myself, to know which issues a beginner can do, to get familiar with this project 🤗

**Comment by bnjbvr** [comment]
Hi! Thanks for opening an issue! We have been using the rustc labeling system, but I get it that it can be a bit confusing for newcomers, especially since we haven't made it explicit: [E-easy](https://github.com/bytecodealliance/cranelift/labels/E-easy) is supposed to show all the good first issues. There are also a label [E-compiler-easy](https://github.com/bytecodealliance/cranelift/labels/E-compiler-easy) for issues that are relatively easy *and* related to compilers, if you're so inclined. In general, all the labels starting with `E-` relate to a level of experience required to tackle the associated issues.

We should probably reword most labels names, since they're not quite telling at the moment :sweat_smile: .

**Comment by Luro02** [comment]
Thanks for pointing me to the issue tags 😊
I think the wording is fine and there is an explanation of them too, but maybe there could be a `Contribution` section in the readme, like in [tokio](https://github.com/tokio-rs/tokio/blob/master/README.md#contributing) and in the guide would be something like `to get started, you can look at issues tagged with 'E-Easy", for more tags and their explanation you can look here`(`E-Easy` would be a link, that applies this tag and `here` would point to an overview)?

**Comment by bnjbvr** [comment]
We do have a section like this in our contributing.md file, but not in the readme! I'll add a small section in there that redirects to the contributing.md file.
