### ISSUE TITLE
Should target-lexicon be updated?

### ISSUE THREAD

**Issue by philipc** [bytecodealliance/cranelift#1292]
`target-lexicon` 0.10.0 has been released, but none of the ecosystem has been updated to use it yet. Since this affects public APIs, I think everything needs to be updated around the same time.

I am planning to do a new `object` release and associated `cranelift-object` update in the near future. Before releasing, should I update it to use the new version of `target-lexicon`? I'm fine with doing a `faerie` PR for this too.

The alternative is to hold off updating `target-lexicon` for now.

**Comment by bnjbvr** [comment]
Yeah, it'd be nice to update the whole ecosystem at once (faerie, object) so we can update target-lexicon in tree without any trouble. Thanks for proposing to do it!

**Comment by sunfishcode** [comment]
As an aside, does anyone have an opinion on whether we should make target-lexicon's enums [nonexhaustive](https://github.com/bytecodealliance/target-lexicon/issues/37), so that adding new kinds of targets doesn't require incompatible semver bumps?

It's also worth mentioning, projects which don't need to look at the target themselves should consider just using strings rather than eagerly resolving them to `Triple` values, which can minimize the number of places that directly depend on target-lexicon.

**Comment by philipc** [comment]
Avoiding incompatible semver bumps would be really nice so I'm all for making them nonexhaustive.

`object` does need to know about binary formats and architectures, but a couple of ways it could avoid using target-lexicon in its public API are:
- go back to using its own enums, and require cranelift-object to translate from target-lexicon
- use its own enums in the public API, but also provide a public API that accepts a triple string and internally uses target-lexicon to interpret the string

I'm not keen on either of those though.
