### ISSUE TITLE
de-public `fn finalize_definitions`

### ISSUE THREAD

**Issue by iximeow** [bytecodealliance/cranelift#1353]
Now that `finalize_definitions` is called by default when finalizing a module (since #1290), calling it in an application using Cranelift is likely either an unintentional second call to `finalize_definitions`, or an outright error. If the lifecycle of finalization is entirely internal to `Module` (as it seems it ought to be), we ought to make this non-public and avoid some misuse.

I happened to trip across this when revisiting some code written before this change was made, where this might have more clearly signalled what changed in the mean time.

**Comment by philipc** [comment]
This is true for `cranelift-faerie` and `cranelift-object`, but I don't think it is true for `cranelift-simplejit`. I'm not very familiar with `cranelift-simplejit` (who uses it?),  but it seems to me that for it you need to call `finalize_definitions`, then run the code, then call `finish` when you are done (e.g. see [rustc_codegen_cranelift](https://github.com/bjorn3/rustc_codegen_cranelift/blob/160dcefab87e6b1feb64b43339657debcd8eee30/src/driver.rs#L65-L87)).

So maybe a better fix is to revert #1290 and handle the `cranelift-object` relocations in `finish` instead of `finalize_definitions`.

Also, I thought you were using `cranelift-faerie`, and I thought it doesn't do anything to finalize anyway? Did I miss something?

**Comment by philipc** [comment]
Could that logic you added in `publish` be moved to `finish` too?

**Comment by iximeow** [comment]
I don't see a reason why not. Pretty sure I picked `finalize_definitions` because it seemed like writing `.eh_frame` is part of finalizing definitions in a module, but it fits with `finish` fine. I'd add that the doc comment on `finalize_definitions` might be better off referencing `cranelift-simplejit` for an example of what applicable logic for `finalize_definitions` is.

**Comment by jyn514** [comment]
>  I'm not very familiar with cranelift-simplejit (who uses it?), but it seems to me that for it you need to call finalize_definitions, then run the code, then call finish when you are done (e.g. see rustc_codegen_cranelift).

Since there's a valid use case for calling `finalize_definitions` before `finish`, is there a reason not to keep both functions as public?

**Comment by philipc** [comment]
> Since there's a valid use case for calling finalize_definitions before finish, is there a reason not to keep both functions as public?

Right, so what I'm proposing is keep them both public, and move `cranelift-object`'s relocation processing to `finish`, and then #1290 is no longer necessary. (This is also what I proposed in  https://github.com/bytecodealliance/cranelift/issues/1288#issuecomment-565753519).

**Comment by jyn514** [comment]
Ok, in that case I think there should be more documentation about what it means to 'finish' a module vs 'finalize_definitions'. I know it's meant to be independent of the backend, but you could give examples that `cranelift-object` and `cranelift-faerie` emits relocations after `finish()` and `cranelift-simplejit` compiles functions after `finalize_definitions`.

**Comment by bnjbvr** [comment]
As a random thought, it would be good to rename both "finish" and "finalize_definitions" into some things that are more self-explanatory and help distinguishing between the twos, if we could.

**Comment by philipc** [comment]
@iximeow I can work on fixing this if you haven't already.

**Comment by iximeow** [comment]
@philipc go for it, i'm pretty sure i have my week cut out for me already
